FROM golang:1.12

RUN apt-get update && apt-get install -y wget && \
    export DOCKERIZE_VERSION=v0.6.1 && \
    wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && \
    tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && \
    rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY . /go/src/coding_challenge_03